apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  namespace: default
  name: rr-rb
subject:
- kind: ServiceAccount
  name: rr-sa
  apiGroup: ""
roleRef:
  kind: Role
  name: rr-role
  apiGroups: rbac.authorization.k8s.io
