kind: RoleBinding​
apiVersion: rbac.authorization.k8s.io/v1​
metadata:
  name: rr-rb
  namespace: default​
subjects:
- kind: ServiceAccount​
  name: rr-sa
  apiGroup: ""​
roleRef:
  kind: Role​
  name: rr-role
  apiGroup: rbac.authorization.k8s.io
